In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn import metrics


In [2]:
diab=datasets.load_diabetes( return_X_y=False, as_frame=False, scaled=True)

In [3]:
diab.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

In [4]:
diab.values()

dict_values([array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]]), array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       1

In [5]:
diab['target']

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [6]:
df_diab = pd.DataFrame(diab['data'],columns = diab['feature_names'])
df_diab

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [7]:
df_diab['target']=diab['target']   #target-> progression of diabetes after one year
df_diab

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  target  
0   -0.002592  0.019907 -0.017646   151.0  
1   -0.039493 -0.068332 -0.092204    75.0  
2   -0.002592  0.002861 -0.025930   141.0  
3    0.034309  0.022688 -0.009362   206.0  
4   -0.002592 -0.031988 -0.046641   135.0  
..        ...       ...       ...     ...  
437 -0.002592  0.031193  0.007207   178.0  
438  0.034309 -0.018114  0.044485   104.0  
439 -0.011080 -0.046883  0.015491   132.0  
440  0.026560  0.044529 -0.025930   220.0  
441 -0.039493 -0.004222  0.003064    57.0  

[442 rows x 11 columns]

In [8]:
diab_model=linear_model.LinearRegression()

In [9]:
X=df_diab[diab['feature_names']]
y=diab['target']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [11]:
diab_model.fit(X_train, y_train)

LinearRegression()

In [12]:
y_pred = diab_model.predict(X_test)
y_pred

array([ 83.27125578, 132.45169661, 166.37995643, 101.05761521,
       154.55395406, 177.65400385, 168.5145878 ,  82.96137881,
        34.25489523, 243.88031697,  88.82416467, 109.13862889,
        80.00059627, 252.92783741, 168.53835489,  95.40730012,
       165.0146951 , 160.06215256,  44.47620242,  45.61835049,
       292.90397461, 199.2102344 , 190.56649903, 156.2338724 ,
       175.51649717, 169.69215495, 227.30186272, 124.95124384,
       116.98561409,  98.58053074, 108.49915305, 123.91939376,
       230.57470442,  58.19808635, 162.33119421, 142.81786022,
       143.7097504 , 127.10648103, 119.00894036, 162.90046969,
       131.89725687,  57.17947879, 155.79219753, 163.54037252,
       206.90755961, 171.70046909, 199.78305531, 243.00958514,
       232.66195834, 218.21533864, 173.4137587 , 197.8389443 ,
       148.58882869, 104.30289901, 162.15704922, 191.43156427,
       286.88885022,  90.85214724,  93.39270034, 110.3187732 ,
       168.92981271, 234.45988087,  95.50327726, 155.50

In [13]:
y_test

array([181., 187., 156.,  65., 237., 181., 242.,  55.,  45., 215.,  64.,
        63.,  65., 277., 235.,  81., 121., 120.,  55.,  57., 230., 173.,
       170., 196., 141.,  84., 248., 131.,  64., 135.,  61., 111., 272.,
        78., 180.,  85.,  97., 140., 145., 109., 135.,  52., 113.,  91.,
       166., 311., 241., 306., 258., 317., 143., 279., 220., 129., 209.,
       281., 281., 114.,  31.,  69., 200., 208.,  94., 200., 134., 332.,
       293.,  72., 168., 153., 200., 232., 140., 141., 152., 185., 118.,
       175., 183., 302., 137., 172.,  55., 103., 158., 276.,  61., 144.,
        63., 127., 261., 122., 198.,  99., 220., 144., 195., 262., 132.,
       189., 191., 150.,  92.,  94., 222., 109.,  74., 142., 104.,  75.,
       210.])

In [14]:
#to calculate the mean absolute error
from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(y_test, y_pred))


41.55582158288005


In [15]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_test, y_pred))


2665.514969261071


In [16]:
#root_mean_squared_error
from sklearn.metrics import root_mean_squared_error
print(root_mean_squared_error(y_test, y_pred))

51.62862548297283


In [17]:
#r^2 score
from sklearn.metrics import r2_score
print(r2_score(y_test, y_pred))

0.5088363908088664


In [18]:
mean_absolute_percentage_error
from sklearn.metrics import mean_absolute_percentage_error
print(mean_absolute_percentage_error(y_test, y_pred))

NameError: name 'mean_absolute_percentage_error' is not defined